### ISSUE TITLE
[REQUEST] EFI for laptop running BigSur

### ISSUE THREAD

**Issue by meghan06** [BearTS/Opencore#3]
CPU: Intel Core m3 8100Y
IGPU: Intel UHD 615
RAM: 8 GB LPDDR3
STORAGE: 64 GB eMMC (using external HDD)
WIFI: Intel(R) Dual Band Wireless-AC 7265
KEYBOARD: PS2 w/ backlight
TOUCHPAD: ELAN

I would like you to purposely not include support for webcam + speaker/mic. I won't be needing them.

Thank you!

**Comment by BearTS** [comment]
@meghan06 
I would not mind working on it. Also it might be helpful if we could communicate through a platform such as Discord to allow for more timely responses while I am working on the OC build for your system

**Comment by meghan06** [comment]
Okay. If you want to know the specific hardware model, it is the ASUS Chromebook C425 running MrChromebox Firmware.

**Comment by BearTS** [comment]
@meghan06 Look at https://github.com/stryses/Mi-Laptop-Air12.5-8100Y-Hackintosh
This has very similar specifications to your system

**Comment by meghan06** [comment]
Yes, but we have completely different audio, storage, and WiFi.
https://www.asus.com/laptops/for-home/chromebook/asus-chromebook-c425/techspec/

**Comment by BearTS** [comment]
I am not sure about the storage part, 
But I am pretty sure Audio, as well as WiFi should work, cause its a common kext that is needed for it
Can you tell me what Audio driver is your laptop using? Can you tell me about it specifically
